from turtle import *
screen=Screen()
screen.setup(400,400)
screen.bgcolor('#A703EF')
penup()
circle(50)
dot(20)
goto(0,100)
color('#FA057F')
style=('Arial',40,'Bold')
write("HELLO",font=style,align='center')
right(90)
forward(60)
color("#FA057F")
write("FRIENDS",font=style,align='center')
hideturtle()
